services:
  - type: web
    runtime: python
    name: fastapi-backend
    repo: https://github.com/Manted50/sentiment-analysis-backend
    branch: main
    buildCommand: pip install -r requirements.txt
    preDeployCommand: pytest
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    autoDeployTrigger: 'on'
    numInstances: 1
    plan: free
    envVars:
      - key: ARTIFACTS_PATH
        value: ./artifacts
      - key: JOBLIFE_MODELS
        value: ./artifacts/joblife_models

  - type: web
    runtime: static
    name: frontend
    repo: https://github.com/your-username/your-frontend-repo
    branch: main
    buildCommand: yarn build
    staticPublishPath: ./build
    autoDeployTrigger: 'on'

envVarGroups:
  - name: common-settings
    envVars:
      - key: ENV
        value: production
      - key: DEBUG
        value: false
